name: Github Script
on: [push]
  
    
jobs:
  pullrequest:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/github-script@0.8.0
       with:
         github-token: ${{secrets.GITHUB_TOKEN}}
         script: |
           github.rest.pull.create({
             repo: github.context.repo.repo,
             owner: github.context.repo.owner,
             head: github.context.ref,
             base: "main",
             title: "New pull create based on issue",
             body: "review pull request for changes "
           })
